#Requires -Version 7
<#
.SYNOPSIS
    Provisions the local Auth0 application for the cult-columnist CF worker and writes
    secrets to agents/cult-columnist-cf-worker/.dev.vars so wrangler dev picks them up.

.DESCRIPTION
    1. Runs `terraform init` + `terraform apply` in infra/terraform/environments/local
       using the Auth0 management credentials from .env.dev.
    2. Reads the resulting client_id and client_secret from terraform outputs.
    3. Writes (or overwrites) agents/cult-columnist-cf-worker/.dev.vars with the secrets
       needed for `npm run dev --env local`.

.EXAMPLE
    pwsh -ExecutionPolicy Bypass -File ./scripts/local-auth0.ps1
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot          = Split-Path $PSScriptRoot -Parent
$terraformRunScript = Join-Path $PSScriptRoot "terraform-run.ps1"
$localEnvDir       = Join-Path $repoRoot "infra/terraform/environments/local"
$devVarsPath       = Join-Path $repoRoot "agents/cult-columnist-cf-worker/.dev.vars"

function Write-Step {
    param([string]$Message)
    $ts = Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"
    Write-Host "[$ts] $Message" -ForegroundColor Cyan
}

function Invoke-ChildPwsh {
    param([string[]]$Arguments, [string]$WorkingDirectory = $repoRoot)
    Push-Location $WorkingDirectory
    try {
        & pwsh -NoProfile @Arguments
        if ($LASTEXITCODE -ne 0 -or -not $?) {
            throw "Command failed with exit code $LASTEXITCODE"
        }
    } finally {
        Pop-Location
    }
}

function Get-TerraformOutput {
    param([string]$Name)
    Push-Location $localEnvDir
    try {
        $value = (& terraform output -raw -no-color $Name 2>&1)
        if ($LASTEXITCODE -ne 0 -or -not $?) {
            throw "terraform output '$Name' failed: $value"
        }

        $valueText = [string]$value
        if ($valueText -match "No outputs found|No state file was found") {
            throw "terraform output '$Name' is unavailable: $valueText"
        }

        return $value.Trim()
    } finally {
        Pop-Location
    }
}

# 1. Terraform init + apply
Write-Step "Initialising local Terraform environment"
Invoke-ChildPwsh -Arguments @(
    "-File", $terraformRunScript,
    "-Environment", "local",
    "-Operation", "init",
    "-LoadEnvFiles"
)

Write-Step "Applying local Terraform (creates/updates Auth0 app)"
Invoke-ChildPwsh -Arguments @(
    "-File", $terraformRunScript,
    "-Environment", "local",
    "-Operation", "apply",
    "-LoadEnvFiles",
    "-AutoApprove"
)

# 2. Read outputs
Write-Step "Reading Terraform outputs"
$auth0Domain       = Get-TerraformOutput "auth0_domain"
$auth0ClientId     = Get-TerraformOutput "auth0_client_id"
$auth0ClientSecret = Get-TerraformOutput "auth0_client_secret"

if ([string]::IsNullOrWhiteSpace($auth0Domain) -or
    [string]::IsNullOrWhiteSpace($auth0ClientId) -or
    [string]::IsNullOrWhiteSpace($auth0ClientSecret)) {
    throw "One or more required Terraform outputs were empty. Check the local environment apply succeeded."
}

# 3. Write .dev.vars
Write-Step "Writing $devVarsPath"

$devVarsContent = @"
# Auto-generated by scripts/local-auth0.ps1 - do not commit.
# Re-run the script to refresh after Auth0 credentials are rotated.
AUTH0_DOMAIN=$auth0Domain
AUTH0_CLIENT_ID=$auth0ClientId
AUTH0_CLIENT_SECRET=$auth0ClientSecret
"@

Set-Content -Path $devVarsPath -Value $devVarsContent -Encoding UTF8 -NoNewline

Write-Step "Done. .dev.vars written. Start the worker with:"
Write-Host "  cd agents/cult-columnist-cf-worker" -ForegroundColor Green
Write-Host "  npm run dev" -ForegroundColor Green
Write-Host ""
Write-Host "Then open: http://local.freedomtimes.news:8787/ui" -ForegroundColor Green
